[#ftl]
[@b.grid width="100%" items=sessionActivitys var="sessionActivity" id="sessionActivityListTable" target="sessionActivityResult" sortable="true"]
	[@b.row]
		[@b.col width="5%" name="序号"]${sessionActivity_index+1}[/@]
		[@b.col width="20%" name="登录名(姓名)" property="name"]${sessionActivity.name}(${sessionActivity.fullname})[/@]
		[@b.col width="15%" name="登录时间"  property="loginAt"]${sessionActivity.loginAt?string("yy-MM-dd HH:mm")}[/@]
		[@b.col width="15%" name="退出时间" property="logoutAt"]${sessionActivity.logoutAt?string("yy-MM-dd HH:mm")}[/@]
		[@b.col width="10%" name="在线时间" property="onlineTime"]${(sessionActivity.onlineTime/60000)?int}分${(sessionActivity.onlineTime/1000)%60}秒[/@]
		[@b.col name="ip" property="host"/]
		[@b.col name="操作系统" property="os"/]
		[@b.col name="用户代理" property="agent"/]
		[@b.col name="备注" property="remark"/]
	[/@]
[/@]