[#ftl]
[@b.grid  ]
	[@b.row]
		[@b.col name="登录名" sort="sessionActivity.name"]${logonStat[0]}[/@]
		[@b.col name="姓名" sort="sessionActivity.fullname"]${logonStat[1]}[/@]
		[@b.col name="登录次数" sort="count(sessionActivity.name)"][#if logonStat[2]!=0][@b.a  href="session-activity!search?sessionActivity.name=${logonStat[0]}&startTime=${Parameters['startTime']!}&endTime=${Parameters['endTime']!}"]${logonStat[2]}[/@][/#if][/@]
	[/@]
[/@]
