[#ftl]
[@b.navmenu title="权限管理"]
	[@b.navitem title="Dashboard" href="index"/]
	[@ems.guard res="/security/user"][@b.navitem title="entity.user" href="/security/user" /][/@]
	[@ems.guard res="/security/role"][@b.navitem title="entity.role" href="/security/role" /][/@]
	[@ems.guard res="/security/menu"][@b.navitem title="entity.menu" href="/security/menu" /][/@]
	[@ems.guard res="/security/resource"][@b.navitem title="entity.resource" href="/security/resource!search?orderBy=resource.name%20asc" /][/@]
	[@ems.guard res="/security/restrict-meta"][@b.navitem title="entity.restrict" href="/security/restrict-meta" /][/@]
	[@b.navitem title="我的账户" href="/security/my?nav=true" /]
[/@]