[#ftl]
[@b.navmenu title="会话监控管理"]
	[@b.navitem title="当前会话" href="monitor!index"/]
	[@b.navitem title="会话配置" href="monitor!profiles" /]
	[@b.navitem title="历史会话" href="sessioninfo-log" /]
	[@b.navitem title="访问日志" href="monitor!accesslogs?ordreBy=duration%20desc" /]
[/@]