create table ems_business_log_details (id number(19,0) not null, content clob, log_id number(19,0), primary key (id));
create table ems_business_logs (id number(19,0) not null, agent varchar2(100 char), entry varchar2(200 char) not null, ip varchar2(100 char), operate_at timestamp not null, operation varchar2(200 char) not null, operator varchar2(50 char) not null, resrc varchar2(100 char) not null, detail_id number(19,0), primary key (id));
create table ems_code_categories (id number(10,0) not null, name varchar2(50 char) not null unique, parent_id number(10,0), primary key (id));
create table ems_code_metas (id number(19,0) not null, class_name varchar2(100 char) not null, name varchar2(50 char) not null unique, title varchar2(100 char) not null, category_id number(10,0) not null, primary key (id));
create table ems_code_scripts (id number(19,0) not null, created_at timestamp, updated_at timestamp, attr varchar2(20 char) not null, code_class_name varchar2(100 char) not null, code_name varchar2(40 char) not null, description varchar2(100 char) not null, script varchar2(500 char) not null, primary key (id));
create table ems_entity_metas (id number(19,0) not null, comments varchar2(255 char) not null, name varchar2(255 char) not null, remark varchar2(500 char), primary key (id));
create table ems_property_config_items (id number(19,0) not null, description varchar2(500 char) not null, name varchar2(100 char) not null, type varchar2(500 char) not null, value varchar2(500 char) not null, primary key (id));
create table ems_property_metas (id number(19,0) not null, comments varchar2(40 char), name varchar2(255 char) not null, remark varchar2(100 char), type varchar2(255 char) not null, meta_id number(19,0) not null, primary key (id));
create table ems_rule_config_params (id number(19,0) not null, value varchar2(500 char) not null, config_id number(19,0) not null, param_id number(19,0) not null, primary key (id));
create table ems_rule_configs (id number(19,0) not null, created_at timestamp, updated_at timestamp, enabled number(1,0) not null, rule_id number(19,0) not null, primary key (id));
create table ems_rule_parameters (id number(19,0) not null, description varchar2(100 char) not null, name varchar2(100 char) not null, title varchar2(100 char) not null, type varchar2(100 char) not null, parent_id number(19,0), rule_id number(19,0), primary key (id));
create table ems_rules (id number(19,0) not null, created_at timestamp, updated_at timestamp, business varchar2(100 char) not null, description varchar2(300 char) not null, enabled number(1,0) not null, factory varchar2(50 char) not null, name varchar2(100 char) not null unique, service_name varchar2(80 char) not null, primary key (id));
create table se_access_logs (id number(19,0) not null, begin_at timestamp not null, end_at timestamp not null, resrc varchar2(255 char) not null, sessionid varchar2(255 char) not null, username varchar2(255 char) not null, primary key (id));
create table se_authorities (id number(19,0) not null, group_id number(19,0) not null, resource_id number(19,0) not null, primary key (id));
create table se_group_members (id number(19,0) not null, created_at timestamp, updated_at timestamp, granter number(1,0) not null, manager number(1,0) not null, member number(1,0) not null, group_id number(19,0) not null, user_id number(19,0) not null, primary key (id));
create table se_group_profiles (id number(19,0) not null, group_id number(19,0), primary key (id));
create table se_group_properties (id number(19,0) not null, value varchar2(1000 char), meta_id number(19,0) not null, profile_id number(19,0) not null, primary key (id));
create table se_groups (id number(19,0) not null, code varchar2(30 char) not null, created_at timestamp, dynamic number(1,0) not null, enabled number(1,0) not null, name varchar2(100 char) not null unique, remark varchar2(255 char), updated_at timestamp, owner_id number(19,0) not null, parent_id number(19,0), primary key (id));
create table se_menu_profiles (id number(19,0) not null, enabled number(1,0) not null, name varchar2(50 char) not null unique, group_id number(19,0) not null, primary key (id));
create table se_menus (id number(19,0) not null, code varchar2(30 char) not null, enabled number(1,0) not null, entry varchar2(255 char), name varchar2(100 char) not null, remark varchar2(255 char), title varchar2(100 char) not null, parent_id number(19,0), profile_id number(19,0) not null, primary key (id));
create table se_menus_resources (menu_id number(19,0) not null, resource_id number(19,0) not null, primary key (menu_id, resource_id));
create table se_property_metas (id number(19,0) not null, key_name varchar2(20 char), multiple number(1,0) not null, name varchar2(50 char) not null unique, property_names varchar2(100 char), remark varchar2(255 char) not null, required number(1,0) not null, source varchar2(200 char), value_type varchar2(100 char) not null, primary key (id));
create table se_resources (id number(19,0) not null, enabled number(1,0) not null, entry number(1,0) not null, name varchar2(100 char) not null unique, remark varchar2(100 char), scope number(10,0) not null, title varchar2(100 char) not null, primary key (id));
create table se_restrict_entities (id number(19,0) not null, name varchar2(255 char), remark varchar2(255 char), type varchar2(255 char), primary key (id));
create table se_restrictions (id number(19,0) not null, content varchar2(600 char) not null, enabled number(1,0) not null, remark varchar2(200 char), resrc varchar2(200 char), entity_id number(19,0) not null, group_id number(19,0), user_id number(19,0), primary key (id));
create table se_session_profiles (id number(19,0) not null, capacity number(10,0) not null, inactive_interval number(10,0) not null, user_max_sessions number(10,0) not null, group_id number(19,0) not null, primary key (id));
create table se_session_stats (id number(19,0) not null, capacity number(10,0) not null, category varchar2(255 char) not null, inactive_interval number(10,0) not null, on_line number(10,0), stat_at timestamp not null, user_max_sessions number(10,0) not null, primary key (id));
create table se_sessioninfo_logs (id varchar2(255 char) not null, agent varchar2(50 char), fullname varchar2(50 char) not null, ip varchar2(100 char), login_at timestamp not null, logout_at timestamp not null, online_time number(19,0) not null, os varchar2(50 char), remark varchar2(100 char), username varchar2(40 char) not null, primary key (id));
create table se_sessioninfoes (id varchar2(255 char) not null, agent varchar2(50 char), category varchar2(50 char), expired_at timestamp, fullname varchar2(50 char) not null, ip varchar2(100 char), last_access_at timestamp, login_at timestamp not null, os varchar2(50 char), remark varchar2(100 char), username varchar2(40 char) not null, primary key (id));
create table se_user_profiles (id number(19,0) not null, user_id number(19,0), primary key (id));
create table se_user_properties (id number(19,0) not null, value varchar2(1000 char), meta_id number(19,0) not null, profile_id number(19,0) not null, primary key (id));
create table se_users (id number(19,0) not null, created_at timestamp, updated_at timestamp, effect_at timestamp not null, enabled number(1,0) not null, fullname varchar2(50 char) not null, invalid_at timestamp, mail varchar2(255 char) not null, name varchar2(40 char) not null unique, password varchar2(100 char) not null, password_expired_at timestamp, remark varchar2(255 char), creator_id number(19,0), primary key (id));
alter table ems_business_log_details add constraint FK5085C53CB554E7E5 foreign key (log_id) references ems_business_logs;
alter table ems_business_logs add constraint FK3289325A199B50E9 foreign key (detail_id) references ems_business_log_details;
alter table ems_code_categories add constraint FK3934D03AF0A5758D foreign key (parent_id) references ems_code_categories;
alter table ems_code_metas add constraint FK3D1FC630D0E770B9 foreign key (category_id) references ems_code_categories;
alter table ems_property_metas add constraint FK36E44E188EFB861B foreign key (meta_id) references ems_entity_metas;
alter table ems_rule_config_params add constraint FK88D1E11424380613 foreign key (param_id) references ems_rule_parameters;
alter table ems_rule_config_params add constraint FK88D1E1147E3855E2 foreign key (config_id) references ems_rule_configs;
alter table ems_rule_configs add constraint FK7172A22D5B0F821 foreign key (rule_id) references ems_rules;
alter table ems_rule_parameters add constraint FKA6B7399D5B0F821 foreign key (rule_id) references ems_rules;
alter table ems_rule_parameters add constraint FKA6B739959CC44D6 foreign key (parent_id) references ems_rule_parameters;
alter table se_authorities add constraint FK964E94B4F5DE1217 foreign key (group_id) references se_groups;
alter table se_authorities add constraint FK964E94B4B396151D foreign key (resource_id) references se_resources;
alter table se_group_members add constraint FKD501E02C590D297D foreign key (user_id) references se_users;
alter table se_group_members add constraint FKD501E02CF5DE1217 foreign key (group_id) references se_groups;
alter table se_group_profiles add constraint FKB6327737F5DE1217 foreign key (group_id) references se_groups;
alter table se_group_properties add constraint FKFDF7B940D95AEF63 foreign key (profile_id) references se_group_profiles;
alter table se_group_properties add constraint FKFDF7B94047BF7CD7 foreign key (meta_id) references se_property_metas;
alter table se_groups add constraint FKEE42686153164C0C foreign key (parent_id) references se_groups;
alter table se_groups add constraint FKEE426861C4F3D995 foreign key (owner_id) references se_users;
alter table se_menu_profiles add constraint FK99C2CB9DF5DE1217 foreign key (group_id) references se_groups;
alter table se_menus add constraint FK314882C7FEDB7EED foreign key (profile_id) references se_menu_profiles;
alter table se_menus add constraint FK314882C76FE76A3D foreign key (parent_id) references se_menus;
alter table se_menus_resources add constraint FK48E2AEAD2D262568 foreign key (menu_id) references se_menus;
alter table se_menus_resources add constraint FK48E2AEADB396151D foreign key (resource_id) references se_resources;
alter table se_restrictions add constraint FKB83F16F467F13DE5 foreign key (entity_id) references se_restrict_entities;
alter table se_restrictions add constraint FKB83F16F4590D297D foreign key (user_id) references se_users;
alter table se_restrictions add constraint FKB83F16F4F5DE1217 foreign key (group_id) references se_groups;
alter table se_session_profiles add constraint FKBBF365C0F5DE1217 foreign key (group_id) references se_groups;
alter table se_user_profiles add constraint FK60AB6EB1590D297D foreign key (user_id) references se_users;
alter table se_user_properties add constraint FKEE10BA3A285E8807 foreign key (profile_id) references se_user_profiles;
alter table se_user_properties add constraint FKEE10BA3A47BF7CD7 foreign key (meta_id) references se_property_metas;
alter table se_users add constraint FK31BF79DBB4092D7C foreign key (creator_id) references se_users;
create sequence seq_ems_business_log_details start with 1 increment by 1;
create sequence seq_ems_business_logs start with 1 increment by 1;
create sequence seq_ems_code_categories start with 1 increment by 1;
create sequence seq_ems_code_metas start with 1 increment by 1;
create sequence seq_ems_code_scripts start with 1 increment by 1;
create sequence seq_ems_entity_metas start with 1 increment by 1;
create sequence seq_ems_property_config_items start with 1 increment by 1;
create sequence seq_ems_property_metas start with 1 increment by 1;
create sequence seq_ems_rule_config_params start with 1 increment by 1;
create sequence seq_ems_rule_configs start with 1 increment by 1;
create sequence seq_ems_rule_parameters start with 1 increment by 1;
create sequence seq_ems_rules start with 1 increment by 1;
create sequence seq_se_access_logs start with 1 increment by 1;
create sequence seq_se_authorities start with 1 increment by 1;
create sequence seq_se_group_members start with 1 increment by 1;
create sequence seq_se_group_profiles start with 1 increment by 1;
create sequence seq_se_group_properties start with 1 increment by 1;
create sequence seq_se_groups start with 1 increment by 1;
create sequence seq_se_menu_profiles start with 1 increment by 1;
create sequence seq_se_menus start with 1 increment by 1;
create sequence seq_se_property_metas start with 1 increment by 1;
create sequence seq_se_resources start with 1 increment by 1;
create sequence seq_se_restrict_entities start with 1 increment by 1;
create sequence seq_se_restrictions start with 1 increment by 1;
create sequence seq_se_session_profiles start with 1 increment by 1;
create sequence seq_se_session_stats start with 1 increment by 1;
create sequence seq_se_user_profiles start with 1 increment by 1;
create sequence seq_se_user_properties start with 1 increment by 1;
create sequence seq_se_users start with 1 increment by 1;
