[#ftl]
[@b.head/]
[@b.toolbar title="修改参数信息"]bar.addBack("${b.text("action.back")}");[/@]
[@b.form action="!save" title="数据限制参数" theme="list"]
	[@b.textfield label="common.name" name="propertyMeta.name" value="${propertyMeta.name!}" required="true" maxlength="50"/]
	[@b.textfield label="标题" name="propertyMeta.remark" value="${propertyMeta.remark!}" required="true" maxlength="50"/]
	[@b.textfield label="类型" name="propertyMeta.valueType" value="${propertyMeta.valueType!}" required="true" maxlength="100"/]
	[@b.textfield label="数据源" name="propertyMeta.source" value="${(propertyMeta.source)!}" style="width:400px;" maxlength="100" comment="java.lang中的基本类型，此处可以为空"/]
	[@b.textfield label="主键属性" name="propertyMeta.keyName" value="${(propertyMeta.keyName)!}" maxlength="40"/]
	[@b.textfield label="其它显示属性" name="propertyMeta.propertyNames" value="${(propertyMeta.propertyNames)!}" maxlength="100"  /]
	[@b.radios label="是否允许多值" name="propertyMeta.multiple"  value=propertyMeta.multiple/]
	[#--[@b.select2 label="restriction.entities" required="true" name1st="Entitys" name2nd="entityId" items1st=entities items2nd=propertyMeta.entities /]--]
	[@b.formfoot]
		<input type="hidden" name="propertyMeta.id" value="${(propertyMeta.id)!}"/>
		[@b.reset/]&nbsp;&nbsp;[@b.submit value="action.submit" /]
	[/@]
</table>
[/@]
[@b.foot/]