[#ftl]
[@b.head/]
[#include "../nav.ftl"/]
[@sj.tabbedpanel id="tabs"]
	[@sj.tab id="tab1" label="限制模式" href="${b.url('!patterns')}"/]
	[@sj.tab id="tab2" label="限制实体和参数" href="${b.url('!fields')}"/]
[/@]
[@b.foot/]
