[#ftl]
[@b.grid items=sessioninfoLogs var="sessioninfoLog"]
	[@b.row]
		[@b.col width="5%" title="序号"]${sessioninfoLog_index+1}[/@]
		[@b.col width="20%" title="sessioninfo.username" property="username"]${sessioninfoLog.username?html}(${sessioninfoLog.fullname?html})[/@]
		[@b.col width="15%" title="sessioninfo.loginAt"  property="loginAt"]${sessioninfoLog.loginAt?string("yy-MM-dd HH:mm:ss")}[/@]
		[@b.col width="15%" title="sessioninfo.logoutAt" property="logoutAt"]${sessioninfoLog.logoutAt?string("yy-MM-dd HH:mm:ss")}[/@]
		[@b.col width="10%" title="sessioninfo.onlineTime" property="onlineTime"]${(sessioninfoLog.onlineTime/60000)?int}分${(sessioninfoLog.onlineTime/1000)%60}秒[/@]
		[@b.col title="sessioninfo.ip" property="ip"/]
		[@b.col title="sessioninfo.os" property="os"/]
		[@b.col title="sessioninfo.agent" property="agent"/]
		[@b.col title="备注" property="remark"/]
	[/@]
[/@]