[#ftl]
[@b.grid width="95%" items=propertyConfigs var="config"]
	[@b.row]
		[@b.col title="序号" width="7%"]${config_index+1}[/@]
		[@b.col title="参数名称" width="20%" property="name" style="text-align:left"/]
		[@b.col title="类型" width="15%" property="type"/]
		[@b.col title="参数值" width="35%" property="value"/]
		[@b.col title="说明" width="15%" property="description"/]
	[/@]
[/@]