create table ems_business_log_details (id bigint not null, content longtext, log_id bigint, primary key (id));
create table ems_business_logs (id bigint not null, agent varchar(100), entry varchar(200) not null, ip varchar(100), operate_at datetime not null, operation varchar(200) not null, operator varchar(50) not null, resrc varchar(100) not null, detail_id bigint, primary key (id));
create table ems_code_categories (id integer not null, name varchar(50) not null unique, parent_id integer, primary key (id));
create table ems_code_metas (id bigint not null, class_name varchar(100) not null, name varchar(50) not null unique, title varchar(100) not null, category_id integer not null, primary key (id));
create table ems_code_scripts (id bigint not null, created_at datetime, updated_at datetime, attr varchar(20) not null, code_class_name varchar(100) not null, code_name varchar(40) not null, description varchar(100) not null, script varchar(500) not null, primary key (id));
create table ems_entity_metas (id bigint not null, comments varchar(255) not null, name varchar(255) not null, remark varchar(500), primary key (id));
create table ems_property_config_items (id bigint not null, description varchar(500) not null, name varchar(100) not null, type varchar(500) not null, value varchar(500) not null, primary key (id));
create table ems_property_metas (id bigint not null, comments varchar(40), name varchar(255) not null, remark varchar(100), type varchar(255) not null, meta_id bigint not null, primary key (id));
create table ems_rule_config_params (id bigint not null, value varchar(500) not null, config_id bigint not null, param_id bigint not null, primary key (id));
create table ems_rule_configs (id bigint not null, created_at datetime, updated_at datetime, enabled bit not null, rule_id bigint not null, primary key (id));
create table ems_rule_parameters (id bigint not null, description varchar(100) not null, name varchar(100) not null, title varchar(100) not null, type varchar(100) not null, parent_id bigint, rule_id bigint, primary key (id));
create table ems_rules (id bigint not null, created_at datetime, updated_at datetime, business varchar(100) not null, description varchar(300) not null, enabled bit not null, factory varchar(50) not null, name varchar(100) not null unique, service_name varchar(80) not null, primary key (id));
create table se_access_logs (id bigint not null, begin_at datetime not null, end_at datetime not null, resrc varchar(255) not null, sessionid varchar(255) not null, username varchar(255) not null, primary key (id));
create table se_authorities (id bigint not null, group_id bigint not null, resource_id bigint not null, primary key (id));
create table se_group_members (id bigint not null, created_at datetime, updated_at datetime, granter bit not null, manager bit not null, member bit not null, group_id bigint not null, user_id bigint not null, primary key (id));
create table se_group_profiles (id bigint not null, group_id bigint, primary key (id));
create table se_group_properties (id bigint not null, value varchar(1000), meta_id bigint not null, profile_id bigint not null, primary key (id));
create table se_groups (id bigint not null, code varchar(30) not null, created_at datetime, dynamic bit not null, enabled bit not null, name varchar(100) not null unique, remark varchar(255), updated_at datetime, owner_id bigint not null, parent_id bigint, primary key (id));
create table se_menu_profiles (id bigint not null, enabled bit not null, name varchar(50) not null unique, group_id bigint not null, primary key (id));
create table se_menus (id bigint not null, code varchar(30) not null, enabled bit not null, entry varchar(255), name varchar(100) not null, remark varchar(255), title varchar(100) not null, parent_id bigint, profile_id bigint not null, primary key (id));
create table se_menus_resources (menu_id bigint not null, resource_id bigint not null, primary key (menu_id, resource_id));
create table se_property_metas (id bigint not null, key_name varchar(20), multiple bit not null, name varchar(50) not null unique, property_names varchar(100), remark varchar(255) not null, required bit not null, source varchar(200), value_type varchar(100) not null, primary key (id));
create table se_resources (id bigint not null, enabled bit not null, entry bit not null, name varchar(100) not null unique, remark varchar(100), scope integer not null, title varchar(100) not null, primary key (id));
create table se_restrict_entities (id bigint not null, name varchar(255), remark varchar(255), type varchar(255), primary key (id));
create table se_restrictions (id bigint not null, content varchar(600) not null, enabled bit not null, remark varchar(200), resrc varchar(200), entity_id bigint not null, group_id bigint, user_id bigint, primary key (id));
create table se_session_profiles (id bigint not null, capacity integer not null, inactive_interval integer not null, user_max_sessions integer not null, group_id bigint not null, primary key (id));
create table se_session_stats (id bigint not null, capacity integer not null, category varchar(255) not null, inactive_interval integer not null, on_line integer, stat_at datetime not null, user_max_sessions integer not null, primary key (id));
create table se_sessioninfo_logs (id varchar(255) not null, agent varchar(50), fullname varchar(50) not null, ip varchar(100), login_at datetime not null, logout_at datetime not null, online_time bigint not null, os varchar(50), remark varchar(100), username varchar(40) not null, primary key (id));
create table se_sessioninfoes (id varchar(255) not null, agent varchar(50), category varchar(50), expired_at datetime, fullname varchar(50) not null, ip varchar(100), last_access_at datetime, login_at datetime not null, os varchar(50), remark varchar(100), username varchar(40) not null, primary key (id));
create table se_user_profiles (id bigint not null, user_id bigint, primary key (id));
create table se_user_properties (id bigint not null, value varchar(1000), meta_id bigint not null, profile_id bigint not null, primary key (id));
create table se_users (id bigint not null, created_at datetime, updated_at datetime, effect_at datetime not null, enabled bit not null, fullname varchar(50) not null, invalid_at datetime, mail varchar(255) not null, name varchar(40) not null unique, password varchar(100) not null, password_expired_at datetime, remark varchar(255), creator_id bigint, primary key (id));
alter table ems_business_log_details add index FK5085C53CB554E7E5 (log_id), add constraint FK5085C53CB554E7E5 foreign key (log_id) references ems_business_logs (id);
alter table ems_business_logs add index FK3289325A199B50E9 (detail_id), add constraint FK3289325A199B50E9 foreign key (detail_id) references ems_business_log_details (id);
alter table ems_code_categories add index FK3934D03AF0A5758D (parent_id), add constraint FK3934D03AF0A5758D foreign key (parent_id) references ems_code_categories (id);
alter table ems_code_metas add index FK3D1FC630D0E770B9 (category_id), add constraint FK3D1FC630D0E770B9 foreign key (category_id) references ems_code_categories (id);
alter table ems_property_metas add index FK36E44E188EFB861B (meta_id), add constraint FK36E44E188EFB861B foreign key (meta_id) references ems_entity_metas (id);
alter table ems_rule_config_params add index FK88D1E11424380613 (param_id), add constraint FK88D1E11424380613 foreign key (param_id) references ems_rule_parameters (id);
alter table ems_rule_config_params add index FK88D1E1147E3855E2 (config_id), add constraint FK88D1E1147E3855E2 foreign key (config_id) references ems_rule_configs (id);
alter table ems_rule_configs add index FK7172A22D5B0F821 (rule_id), add constraint FK7172A22D5B0F821 foreign key (rule_id) references ems_rules (id);
alter table ems_rule_parameters add index FKA6B7399D5B0F821 (rule_id), add constraint FKA6B7399D5B0F821 foreign key (rule_id) references ems_rules (id);
alter table ems_rule_parameters add index FKA6B739959CC44D6 (parent_id), add constraint FKA6B739959CC44D6 foreign key (parent_id) references ems_rule_parameters (id);
alter table se_authorities add index FK964E94B4F5DE1217 (group_id), add constraint FK964E94B4F5DE1217 foreign key (group_id) references se_groups (id);
alter table se_authorities add index FK964E94B4B396151D (resource_id), add constraint FK964E94B4B396151D foreign key (resource_id) references se_resources (id);
alter table se_group_members add index FKD501E02C590D297D (user_id), add constraint FKD501E02C590D297D foreign key (user_id) references se_users (id);
alter table se_group_members add index FKD501E02CF5DE1217 (group_id), add constraint FKD501E02CF5DE1217 foreign key (group_id) references se_groups (id);
alter table se_group_profiles add index FKB6327737F5DE1217 (group_id), add constraint FKB6327737F5DE1217 foreign key (group_id) references se_groups (id);
alter table se_group_properties add index FKFDF7B940D95AEF63 (profile_id), add constraint FKFDF7B940D95AEF63 foreign key (profile_id) references se_group_profiles (id);
alter table se_group_properties add index FKFDF7B94047BF7CD7 (meta_id), add constraint FKFDF7B94047BF7CD7 foreign key (meta_id) references se_property_metas (id);
alter table se_groups add index FKEE42686153164C0C (parent_id), add constraint FKEE42686153164C0C foreign key (parent_id) references se_groups (id);
alter table se_groups add index FKEE426861C4F3D995 (owner_id), add constraint FKEE426861C4F3D995 foreign key (owner_id) references se_users (id);
alter table se_menu_profiles add index FK99C2CB9DF5DE1217 (group_id), add constraint FK99C2CB9DF5DE1217 foreign key (group_id) references se_groups (id);
alter table se_menus add index FK314882C7FEDB7EED (profile_id), add constraint FK314882C7FEDB7EED foreign key (profile_id) references se_menu_profiles (id);
alter table se_menus add index FK314882C76FE76A3D (parent_id), add constraint FK314882C76FE76A3D foreign key (parent_id) references se_menus (id);
alter table se_menus_resources add index FK48E2AEAD2D262568 (menu_id), add constraint FK48E2AEAD2D262568 foreign key (menu_id) references se_menus (id);
alter table se_menus_resources add index FK48E2AEADB396151D (resource_id), add constraint FK48E2AEADB396151D foreign key (resource_id) references se_resources (id);
alter table se_restrictions add index FKB83F16F467F13DE5 (entity_id), add constraint FKB83F16F467F13DE5 foreign key (entity_id) references se_restrict_entities (id);
alter table se_restrictions add index FKB83F16F4590D297D (user_id), add constraint FKB83F16F4590D297D foreign key (user_id) references se_users (id);
alter table se_restrictions add index FKB83F16F4F5DE1217 (group_id), add constraint FKB83F16F4F5DE1217 foreign key (group_id) references se_groups (id);
alter table se_session_profiles add index FKBBF365C0F5DE1217 (group_id), add constraint FKBBF365C0F5DE1217 foreign key (group_id) references se_groups (id);
alter table se_user_profiles add index FK60AB6EB1590D297D (user_id), add constraint FK60AB6EB1590D297D foreign key (user_id) references se_users (id);
alter table se_user_properties add index FKEE10BA3A285E8807 (profile_id), add constraint FKEE10BA3A285E8807 foreign key (profile_id) references se_user_profiles (id);
alter table se_user_properties add index FKEE10BA3A47BF7CD7 (meta_id), add constraint FKEE10BA3A47BF7CD7 foreign key (meta_id) references se_property_metas (id);
alter table se_users add index FK31BF79DBB4092D7C (creator_id), add constraint FK31BF79DBB4092D7C foreign key (creator_id) references se_users (id);
create table seq_ems_business_log_details ( next_val bigint );
insert into seq_ems_business_log_details values ( 1 );
create table seq_ems_business_logs ( next_val bigint );
insert into seq_ems_business_logs values ( 1 );
create table seq_ems_code_categories ( next_val bigint );
insert into seq_ems_code_categories values ( 1 );
create table seq_ems_code_metas ( next_val bigint );
insert into seq_ems_code_metas values ( 1 );
create table seq_ems_code_scripts ( next_val bigint );
insert into seq_ems_code_scripts values ( 1 );
create table seq_ems_entity_metas ( next_val bigint );
insert into seq_ems_entity_metas values ( 1 );
create table seq_ems_property_config_items ( next_val bigint );
insert into seq_ems_property_config_items values ( 1 );
create table seq_ems_property_metas ( next_val bigint );
insert into seq_ems_property_metas values ( 1 );
create table seq_ems_rule_config_params ( next_val bigint );
insert into seq_ems_rule_config_params values ( 1 );
create table seq_ems_rule_configs ( next_val bigint );
insert into seq_ems_rule_configs values ( 1 );
create table seq_ems_rule_parameters ( next_val bigint );
insert into seq_ems_rule_parameters values ( 1 );
create table seq_ems_rules ( next_val bigint );
insert into seq_ems_rules values ( 1 );
create table seq_se_access_logs ( next_val bigint );
insert into seq_se_access_logs values ( 1 );
create table seq_se_authorities ( next_val bigint );
insert into seq_se_authorities values ( 1 );
create table seq_se_group_members ( next_val bigint );
insert into seq_se_group_members values ( 1 );
create table seq_se_group_profiles ( next_val bigint );
insert into seq_se_group_profiles values ( 1 );
create table seq_se_group_properties ( next_val bigint );
insert into seq_se_group_properties values ( 1 );
create table seq_se_groups ( next_val bigint );
insert into seq_se_groups values ( 1 );
create table seq_se_menu_profiles ( next_val bigint );
insert into seq_se_menu_profiles values ( 1 );
create table seq_se_menus ( next_val bigint );
insert into seq_se_menus values ( 1 );
create table seq_se_property_metas ( next_val bigint );
insert into seq_se_property_metas values ( 1 );
create table seq_se_resources ( next_val bigint );
insert into seq_se_resources values ( 1 );
create table seq_se_restrict_entities ( next_val bigint );
insert into seq_se_restrict_entities values ( 1 );
create table seq_se_restrictions ( next_val bigint );
insert into seq_se_restrictions values ( 1 );
create table seq_se_session_profiles ( next_val bigint );
insert into seq_se_session_profiles values ( 1 );
create table seq_se_session_stats ( next_val bigint );
insert into seq_se_session_stats values ( 1 );
create table seq_se_user_profiles ( next_val bigint );
insert into seq_se_user_profiles values ( 1 );
create table seq_se_user_properties ( next_val bigint );
insert into seq_se_user_properties values ( 1 );
create table seq_se_users ( next_val bigint );
insert into seq_se_users values ( 1 );
