/*
 * Beangle, Agile Development Scaffold and Toolkits.
 *
 * Copyright © 2005, The Beangle Software.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/org/beangle/ems/app/log/model.proto

package org.beangle.ems.log;

public final class BusinessLogProto {
  private BusinessLogProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface BusinessLogEventOrBuilder extends
      // @@protoc_insertion_point(interface_extends:BusinessLogEvent)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string operator = 1;</code>
     * @return The operator.
     */
    String getOperator();
    /**
     * <code>string operator = 1;</code>
     * @return The bytes for operator.
     */
    com.google.protobuf.ByteString
        getOperatorBytes();

    /**
     * <code>int64 operateAt = 2;</code>
     * @return The operateAt.
     */
    long getOperateAt();

    /**
     * <code>string summary = 3;</code>
     * @return The summary.
     */
    String getSummary();
    /**
     * <code>string summary = 3;</code>
     * @return The bytes for summary.
     */
    com.google.protobuf.ByteString
        getSummaryBytes();

    /**
     * <code>string details = 4;</code>
     * @return The details.
     */
    String getDetails();
    /**
     * <code>string details = 4;</code>
     * @return The bytes for details.
     */
    com.google.protobuf.ByteString
        getDetailsBytes();

    /**
     * <code>string resources = 5;</code>
     * @return The resources.
     */
    String getResources();
    /**
     * <code>string resources = 5;</code>
     * @return The bytes for resources.
     */
    com.google.protobuf.ByteString
        getResourcesBytes();

    /**
     * <code>string ip = 6;</code>
     * @return The ip.
     */
    String getIp();
    /**
     * <code>string ip = 6;</code>
     * @return The bytes for ip.
     */
    com.google.protobuf.ByteString
        getIpBytes();

    /**
     * <code>string agent = 7;</code>
     * @return The agent.
     */
    String getAgent();
    /**
     * <code>string agent = 7;</code>
     * @return The bytes for agent.
     */
    com.google.protobuf.ByteString
        getAgentBytes();

    /**
     * <code>string entry = 8;</code>
     * @return The entry.
     */
    String getEntry();
    /**
     * <code>string entry = 8;</code>
     * @return The bytes for entry.
     */
    com.google.protobuf.ByteString
        getEntryBytes();

    /**
     * <code>int32 level = 9;</code>
     * @return The level.
     */
    int getLevel();

    /**
     * <code>string appName = 10;</code>
     * @return The appName.
     */
    String getAppName();
    /**
     * <code>string appName = 10;</code>
     * @return The bytes for appName.
     */
    com.google.protobuf.ByteString
        getAppNameBytes();
  }
  /**
   * Protobuf type {@code BusinessLogEvent}
   */
  public static final class BusinessLogEvent extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:BusinessLogEvent)
      BusinessLogEventOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use BusinessLogEvent.newBuilder() to construct.
    private BusinessLogEvent(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private BusinessLogEvent() {
      operator_ = "";
      summary_ = "";
      details_ = "";
      resources_ = "";
      ip_ = "";
      agent_ = "";
      entry_ = "";
      appName_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new BusinessLogEvent();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private BusinessLogEvent(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              String s = input.readStringRequireUtf8();

              operator_ = s;
              break;
            }
            case 16: {

              operateAt_ = input.readInt64();
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();

              summary_ = s;
              break;
            }
            case 34: {
              String s = input.readStringRequireUtf8();

              details_ = s;
              break;
            }
            case 42: {
              String s = input.readStringRequireUtf8();

              resources_ = s;
              break;
            }
            case 50: {
              String s = input.readStringRequireUtf8();

              ip_ = s;
              break;
            }
            case 58: {
              String s = input.readStringRequireUtf8();

              agent_ = s;
              break;
            }
            case 66: {
              String s = input.readStringRequireUtf8();

              entry_ = s;
              break;
            }
            case 72: {

              level_ = input.readInt32();
              break;
            }
            case 82: {
              String s = input.readStringRequireUtf8();

              appName_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return BusinessLogProto.internal_static_BusinessLogEvent_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return BusinessLogProto.internal_static_BusinessLogEvent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              BusinessLogEvent.class, Builder.class);
    }

    public static final int OPERATOR_FIELD_NUMBER = 1;
    private volatile Object operator_;
    /**
     * <code>string operator = 1;</code>
     * @return The operator.
     */
    @Override
    public String getOperator() {
      Object ref = operator_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        operator_ = s;
        return s;
      }
    }
    /**
     * <code>string operator = 1;</code>
     * @return The bytes for operator.
     */
    @Override
    public com.google.protobuf.ByteString
        getOperatorBytes() {
      Object ref = operator_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        operator_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int OPERATEAT_FIELD_NUMBER = 2;
    private long operateAt_;
    /**
     * <code>int64 operateAt = 2;</code>
     * @return The operateAt.
     */
    @Override
    public long getOperateAt() {
      return operateAt_;
    }

    public static final int SUMMARY_FIELD_NUMBER = 3;
    private volatile Object summary_;
    /**
     * <code>string summary = 3;</code>
     * @return The summary.
     */
    @Override
    public String getSummary() {
      Object ref = summary_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        summary_ = s;
        return s;
      }
    }
    /**
     * <code>string summary = 3;</code>
     * @return The bytes for summary.
     */
    @Override
    public com.google.protobuf.ByteString
        getSummaryBytes() {
      Object ref = summary_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        summary_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DETAILS_FIELD_NUMBER = 4;
    private volatile Object details_;
    /**
     * <code>string details = 4;</code>
     * @return The details.
     */
    @Override
    public String getDetails() {
      Object ref = details_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        details_ = s;
        return s;
      }
    }
    /**
     * <code>string details = 4;</code>
     * @return The bytes for details.
     */
    @Override
    public com.google.protobuf.ByteString
        getDetailsBytes() {
      Object ref = details_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        details_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RESOURCES_FIELD_NUMBER = 5;
    private volatile Object resources_;
    /**
     * <code>string resources = 5;</code>
     * @return The resources.
     */
    @Override
    public String getResources() {
      Object ref = resources_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        resources_ = s;
        return s;
      }
    }
    /**
     * <code>string resources = 5;</code>
     * @return The bytes for resources.
     */
    @Override
    public com.google.protobuf.ByteString
        getResourcesBytes() {
      Object ref = resources_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        resources_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int IP_FIELD_NUMBER = 6;
    private volatile Object ip_;
    /**
     * <code>string ip = 6;</code>
     * @return The ip.
     */
    @Override
    public String getIp() {
      Object ref = ip_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        ip_ = s;
        return s;
      }
    }
    /**
     * <code>string ip = 6;</code>
     * @return The bytes for ip.
     */
    @Override
    public com.google.protobuf.ByteString
        getIpBytes() {
      Object ref = ip_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        ip_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AGENT_FIELD_NUMBER = 7;
    private volatile Object agent_;
    /**
     * <code>string agent = 7;</code>
     * @return The agent.
     */
    @Override
    public String getAgent() {
      Object ref = agent_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        agent_ = s;
        return s;
      }
    }
    /**
     * <code>string agent = 7;</code>
     * @return The bytes for agent.
     */
    @Override
    public com.google.protobuf.ByteString
        getAgentBytes() {
      Object ref = agent_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        agent_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ENTRY_FIELD_NUMBER = 8;
    private volatile Object entry_;
    /**
     * <code>string entry = 8;</code>
     * @return The entry.
     */
    @Override
    public String getEntry() {
      Object ref = entry_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        entry_ = s;
        return s;
      }
    }
    /**
     * <code>string entry = 8;</code>
     * @return The bytes for entry.
     */
    @Override
    public com.google.protobuf.ByteString
        getEntryBytes() {
      Object ref = entry_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        entry_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LEVEL_FIELD_NUMBER = 9;
    private int level_;
    /**
     * <code>int32 level = 9;</code>
     * @return The level.
     */
    @Override
    public int getLevel() {
      return level_;
    }

    public static final int APPNAME_FIELD_NUMBER = 10;
    private volatile Object appName_;
    /**
     * <code>string appName = 10;</code>
     * @return The appName.
     */
    @Override
    public String getAppName() {
      Object ref = appName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        appName_ = s;
        return s;
      }
    }
    /**
     * <code>string appName = 10;</code>
     * @return The bytes for appName.
     */
    @Override
    public com.google.protobuf.ByteString
        getAppNameBytes() {
      Object ref = appName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        appName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(operator_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, operator_);
      }
      if (operateAt_ != 0L) {
        output.writeInt64(2, operateAt_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(summary_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, summary_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(details_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, details_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(resources_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, resources_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(ip_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, ip_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(agent_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, agent_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(entry_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, entry_);
      }
      if (level_ != 0) {
        output.writeInt32(9, level_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(appName_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 10, appName_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(operator_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, operator_);
      }
      if (operateAt_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, operateAt_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(summary_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, summary_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(details_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, details_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(resources_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, resources_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(ip_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, ip_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(agent_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, agent_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(entry_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, entry_);
      }
      if (level_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(9, level_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(appName_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, appName_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof BusinessLogEvent)) {
        return super.equals(obj);
      }
      BusinessLogEvent other = (BusinessLogEvent) obj;

      if (!getOperator()
          .equals(other.getOperator())) return false;
      if (getOperateAt()
          != other.getOperateAt()) return false;
      if (!getSummary()
          .equals(other.getSummary())) return false;
      if (!getDetails()
          .equals(other.getDetails())) return false;
      if (!getResources()
          .equals(other.getResources())) return false;
      if (!getIp()
          .equals(other.getIp())) return false;
      if (!getAgent()
          .equals(other.getAgent())) return false;
      if (!getEntry()
          .equals(other.getEntry())) return false;
      if (getLevel()
          != other.getLevel()) return false;
      if (!getAppName()
          .equals(other.getAppName())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + OPERATOR_FIELD_NUMBER;
      hash = (53 * hash) + getOperator().hashCode();
      hash = (37 * hash) + OPERATEAT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getOperateAt());
      hash = (37 * hash) + SUMMARY_FIELD_NUMBER;
      hash = (53 * hash) + getSummary().hashCode();
      hash = (37 * hash) + DETAILS_FIELD_NUMBER;
      hash = (53 * hash) + getDetails().hashCode();
      hash = (37 * hash) + RESOURCES_FIELD_NUMBER;
      hash = (53 * hash) + getResources().hashCode();
      hash = (37 * hash) + IP_FIELD_NUMBER;
      hash = (53 * hash) + getIp().hashCode();
      hash = (37 * hash) + AGENT_FIELD_NUMBER;
      hash = (53 * hash) + getAgent().hashCode();
      hash = (37 * hash) + ENTRY_FIELD_NUMBER;
      hash = (53 * hash) + getEntry().hashCode();
      hash = (37 * hash) + LEVEL_FIELD_NUMBER;
      hash = (53 * hash) + getLevel();
      hash = (37 * hash) + APPNAME_FIELD_NUMBER;
      hash = (53 * hash) + getAppName().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static BusinessLogEvent parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static BusinessLogEvent parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static BusinessLogEvent parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static BusinessLogEvent parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static BusinessLogEvent parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static BusinessLogEvent parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static BusinessLogEvent parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static BusinessLogEvent parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static BusinessLogEvent parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static BusinessLogEvent parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static BusinessLogEvent parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static BusinessLogEvent parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(BusinessLogEvent prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code BusinessLogEvent}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:BusinessLogEvent)
        BusinessLogEventOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return BusinessLogProto.internal_static_BusinessLogEvent_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return BusinessLogProto.internal_static_BusinessLogEvent_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                BusinessLogEvent.class, Builder.class);
      }

      // Construct using org.beangle.ems.app.log.BusinessLogProto.BusinessLogEvent.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        operator_ = "";

        operateAt_ = 0L;

        summary_ = "";

        details_ = "";

        resources_ = "";

        ip_ = "";

        agent_ = "";

        entry_ = "";

        level_ = 0;

        appName_ = "";

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return BusinessLogProto.internal_static_BusinessLogEvent_descriptor;
      }

      @Override
      public BusinessLogEvent getDefaultInstanceForType() {
        return BusinessLogEvent.getDefaultInstance();
      }

      @Override
      public BusinessLogEvent build() {
        BusinessLogEvent result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public BusinessLogEvent buildPartial() {
        BusinessLogEvent result = new BusinessLogEvent(this);
        result.operator_ = operator_;
        result.operateAt_ = operateAt_;
        result.summary_ = summary_;
        result.details_ = details_;
        result.resources_ = resources_;
        result.ip_ = ip_;
        result.agent_ = agent_;
        result.entry_ = entry_;
        result.level_ = level_;
        result.appName_ = appName_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof BusinessLogEvent) {
          return mergeFrom((BusinessLogEvent)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(BusinessLogEvent other) {
        if (other == BusinessLogEvent.getDefaultInstance()) return this;
        if (!other.getOperator().isEmpty()) {
          operator_ = other.operator_;
          onChanged();
        }
        if (other.getOperateAt() != 0L) {
          setOperateAt(other.getOperateAt());
        }
        if (!other.getSummary().isEmpty()) {
          summary_ = other.summary_;
          onChanged();
        }
        if (!other.getDetails().isEmpty()) {
          details_ = other.details_;
          onChanged();
        }
        if (!other.getResources().isEmpty()) {
          resources_ = other.resources_;
          onChanged();
        }
        if (!other.getIp().isEmpty()) {
          ip_ = other.ip_;
          onChanged();
        }
        if (!other.getAgent().isEmpty()) {
          agent_ = other.agent_;
          onChanged();
        }
        if (!other.getEntry().isEmpty()) {
          entry_ = other.entry_;
          onChanged();
        }
        if (other.getLevel() != 0) {
          setLevel(other.getLevel());
        }
        if (!other.getAppName().isEmpty()) {
          appName_ = other.appName_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        BusinessLogEvent parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (BusinessLogEvent) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Object operator_ = "";
      /**
       * <code>string operator = 1;</code>
       * @return The operator.
       */
      public String getOperator() {
        Object ref = operator_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          operator_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string operator = 1;</code>
       * @return The bytes for operator.
       */
      public com.google.protobuf.ByteString
          getOperatorBytes() {
        Object ref = operator_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          operator_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string operator = 1;</code>
       * @param value The operator to set.
       * @return This builder for chaining.
       */
      public Builder setOperator(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        operator_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string operator = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearOperator() {

        operator_ = getDefaultInstance().getOperator();
        onChanged();
        return this;
      }
      /**
       * <code>string operator = 1;</code>
       * @param value The bytes for operator to set.
       * @return This builder for chaining.
       */
      public Builder setOperatorBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        operator_ = value;
        onChanged();
        return this;
      }

      private long operateAt_ ;
      /**
       * <code>int64 operateAt = 2;</code>
       * @return The operateAt.
       */
      @Override
      public long getOperateAt() {
        return operateAt_;
      }
      /**
       * <code>int64 operateAt = 2;</code>
       * @param value The operateAt to set.
       * @return This builder for chaining.
       */
      public Builder setOperateAt(long value) {

        operateAt_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 operateAt = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearOperateAt() {

        operateAt_ = 0L;
        onChanged();
        return this;
      }

      private Object summary_ = "";
      /**
       * <code>string summary = 3;</code>
       * @return The summary.
       */
      public String getSummary() {
        Object ref = summary_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          summary_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string summary = 3;</code>
       * @return The bytes for summary.
       */
      public com.google.protobuf.ByteString
          getSummaryBytes() {
        Object ref = summary_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          summary_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string summary = 3;</code>
       * @param value The summary to set.
       * @return This builder for chaining.
       */
      public Builder setSummary(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        summary_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string summary = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearSummary() {

        summary_ = getDefaultInstance().getSummary();
        onChanged();
        return this;
      }
      /**
       * <code>string summary = 3;</code>
       * @param value The bytes for summary to set.
       * @return This builder for chaining.
       */
      public Builder setSummaryBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        summary_ = value;
        onChanged();
        return this;
      }

      private Object details_ = "";
      /**
       * <code>string details = 4;</code>
       * @return The details.
       */
      public String getDetails() {
        Object ref = details_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          details_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string details = 4;</code>
       * @return The bytes for details.
       */
      public com.google.protobuf.ByteString
          getDetailsBytes() {
        Object ref = details_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          details_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string details = 4;</code>
       * @param value The details to set.
       * @return This builder for chaining.
       */
      public Builder setDetails(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        details_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string details = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearDetails() {

        details_ = getDefaultInstance().getDetails();
        onChanged();
        return this;
      }
      /**
       * <code>string details = 4;</code>
       * @param value The bytes for details to set.
       * @return This builder for chaining.
       */
      public Builder setDetailsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        details_ = value;
        onChanged();
        return this;
      }

      private Object resources_ = "";
      /**
       * <code>string resources = 5;</code>
       * @return The resources.
       */
      public String getResources() {
        Object ref = resources_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          resources_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string resources = 5;</code>
       * @return The bytes for resources.
       */
      public com.google.protobuf.ByteString
          getResourcesBytes() {
        Object ref = resources_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          resources_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string resources = 5;</code>
       * @param value The resources to set.
       * @return This builder for chaining.
       */
      public Builder setResources(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        resources_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string resources = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearResources() {

        resources_ = getDefaultInstance().getResources();
        onChanged();
        return this;
      }
      /**
       * <code>string resources = 5;</code>
       * @param value The bytes for resources to set.
       * @return This builder for chaining.
       */
      public Builder setResourcesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        resources_ = value;
        onChanged();
        return this;
      }

      private Object ip_ = "";
      /**
       * <code>string ip = 6;</code>
       * @return The ip.
       */
      public String getIp() {
        Object ref = ip_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          ip_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string ip = 6;</code>
       * @return The bytes for ip.
       */
      public com.google.protobuf.ByteString
          getIpBytes() {
        Object ref = ip_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          ip_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string ip = 6;</code>
       * @param value The ip to set.
       * @return This builder for chaining.
       */
      public Builder setIp(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        ip_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string ip = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearIp() {

        ip_ = getDefaultInstance().getIp();
        onChanged();
        return this;
      }
      /**
       * <code>string ip = 6;</code>
       * @param value The bytes for ip to set.
       * @return This builder for chaining.
       */
      public Builder setIpBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        ip_ = value;
        onChanged();
        return this;
      }

      private Object agent_ = "";
      /**
       * <code>string agent = 7;</code>
       * @return The agent.
       */
      public String getAgent() {
        Object ref = agent_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          agent_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string agent = 7;</code>
       * @return The bytes for agent.
       */
      public com.google.protobuf.ByteString
          getAgentBytes() {
        Object ref = agent_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          agent_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string agent = 7;</code>
       * @param value The agent to set.
       * @return This builder for chaining.
       */
      public Builder setAgent(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        agent_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string agent = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearAgent() {

        agent_ = getDefaultInstance().getAgent();
        onChanged();
        return this;
      }
      /**
       * <code>string agent = 7;</code>
       * @param value The bytes for agent to set.
       * @return This builder for chaining.
       */
      public Builder setAgentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        agent_ = value;
        onChanged();
        return this;
      }

      private Object entry_ = "";
      /**
       * <code>string entry = 8;</code>
       * @return The entry.
       */
      public String getEntry() {
        Object ref = entry_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          entry_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string entry = 8;</code>
       * @return The bytes for entry.
       */
      public com.google.protobuf.ByteString
          getEntryBytes() {
        Object ref = entry_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          entry_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string entry = 8;</code>
       * @param value The entry to set.
       * @return This builder for chaining.
       */
      public Builder setEntry(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        entry_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string entry = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearEntry() {

        entry_ = getDefaultInstance().getEntry();
        onChanged();
        return this;
      }
      /**
       * <code>string entry = 8;</code>
       * @param value The bytes for entry to set.
       * @return This builder for chaining.
       */
      public Builder setEntryBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        entry_ = value;
        onChanged();
        return this;
      }

      private int level_ ;
      /**
       * <code>int32 level = 9;</code>
       * @return The level.
       */
      @Override
      public int getLevel() {
        return level_;
      }
      /**
       * <code>int32 level = 9;</code>
       * @param value The level to set.
       * @return This builder for chaining.
       */
      public Builder setLevel(int value) {

        level_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 level = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearLevel() {

        level_ = 0;
        onChanged();
        return this;
      }

      private Object appName_ = "";
      /**
       * <code>string appName = 10;</code>
       * @return The appName.
       */
      public String getAppName() {
        Object ref = appName_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          appName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string appName = 10;</code>
       * @return The bytes for appName.
       */
      public com.google.protobuf.ByteString
          getAppNameBytes() {
        Object ref = appName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          appName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string appName = 10;</code>
       * @param value The appName to set.
       * @return This builder for chaining.
       */
      public Builder setAppName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        appName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string appName = 10;</code>
       * @return This builder for chaining.
       */
      public Builder clearAppName() {

        appName_ = getDefaultInstance().getAppName();
        onChanged();
        return this;
      }
      /**
       * <code>string appName = 10;</code>
       * @param value The bytes for appName to set.
       * @return This builder for chaining.
       */
      public Builder setAppNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        appName_ = value;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }

      // @@protoc_insertion_point(builder_scope:BusinessLogEvent)
    }

    // @@protoc_insertion_point(class_scope:BusinessLogEvent)
    private static final BusinessLogEvent DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new BusinessLogEvent();
    }

    public static BusinessLogEvent getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<BusinessLogEvent>
        PARSER = new com.google.protobuf.AbstractParser<BusinessLogEvent>() {
      @Override
      public BusinessLogEvent parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BusinessLogEvent(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<BusinessLogEvent> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<BusinessLogEvent> getParserForType() {
      return PARSER;
    }

    @Override
    public BusinessLogEvent getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BusinessLogEvent_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BusinessLogEvent_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n6src/main/resources/org/beangle/ems/app" +
      "/log/model.proto\"\266\001\n\020BusinessLogEvent\022\020\n" +
      "\010operator\030\001 \001(\t\022\021\n\toperateAt\030\002 \001(\003\022\017\n\007su" +
      "mmary\030\003 \001(\t\022\017\n\007details\030\004 \001(\t\022\021\n\tresource" +
      "s\030\005 \001(\t\022\n\n\002ip\030\006 \001(\t\022\r\n\005agent\030\007 \001(\t\022\r\n\005en" +
      "try\030\010 \001(\t\022\r\n\005level\030\t \001(\005\022\017\n\007appName\030\n \001(" +
      "\tB+\n\027org.beangle.ems.app.logB\020BusinessLo" +
      "gProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_BusinessLogEvent_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_BusinessLogEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BusinessLogEvent_descriptor,
        new String[] { "Operator", "OperateAt", "Summary", "Details", "Resources", "Ip", "Agent", "Entry", "Level", "AppName", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
