[#ftl]
[@b.navmenu title="权限管理"]
	[@b.navitem title="控制台" href="index"/]
	[@bs.guard res="/security/user"][@b.navitem title="用户" href="user" /][/@]
	[@bs.guard res="/security/group"][@b.navitem title="用户组" href="group" /][/@]
	[@bs.guard res="/security/menu"][@b.navitem title="菜单" href="menu" /][/@]
	[@bs.guard res="/security/resource"][@b.navitem title="资源" href="resource" /][/@]
	[@bs.guard res="/security/restrict-meta"][@b.navitem title="数据限制" href="restrict-meta" /][/@]
	[@bs.guard res="/security/monitor"][@b.navitem title="系统监控" href="monitor" /][/@]
	[@b.navitem title="我的账户" href="my" /]
[/@]