[#ftl]
[@b.qform name="userSearchForm" action="!search" title="ui.searchForm" target="userlist"]
	[@b.qfields names="user.name,user.fullname,user.creator.fullname,groupName;entity.group"/]
	[@b.qselect name="categoryId" title="entity.userCategory" items=categories empty="..." /]
	[@b.qselect name="user.status" title="common.status" items={'1':'${b.text("action.activate")}','0':'${b.text("action.freeze")}'}/]
[/@]