[#ftl]
<div id="stats">
[@b.module title="用户统计"]
	[@b.grid  items=groupStat var="stat" width="94%" ]
		[@b.row]
			[@b.col title="类别"]${categories.get(stat[0]).title}[/@]
			[@b.col title="状态"]${stat[1]?string("激活","禁用")}[/@]
			[@b.col title="数量"]${stat[2]}[/@]
		[/@]
	[/@]
[/@]

[@b.module title="用户组统计"]
	[@b.grid width="94%" items=groupStat var="stat" ]
		[@b.row]
			[@b.col title="类别"]${categories.get(stat[0]).title}[/@]
			[@b.col title="状态"]${stat[1]?string("激活","禁用")}[/@]
			[@b.col title="数量"]${stat[2]}[/@]
		[/@]
	[/@]
[/@]

[@b.module title="系统资源"]
	[@b.grid width="94%" items=resourceStat var="stat" ]
		[@b.row]
			[@b.col title="状态"]${stat[0]?string("激活","禁用")}[/@]
			[@b.col title="资源数"]${stat[1]}[/@]
		[/@]
	[/@]
[/@]

[@b.module title="菜单设置"]
	[@b.grid width="94%" items=menuProfiles var="profile" sortable="false"]
		[@b.row]
			[@b.col title="类别" property="name"/]
			[@b.col title="状态/菜单数"][#list menuStats.get(profile.id) as stat]${stat[0]?string("激活","禁用")}/${stat[1]}&nbsp;[/#list][/@]
		[/@]
	[/@]
[/@]

[@b.module title="数据权限"]
	限制模式数量:${patternStat[0]}<br/>
	模式参数数量:${paramStat[0]}<br/>
[/@]
</div>