create table ems_business_log_details (id int8 not null, content text, log_id int8, primary key (id));
create table ems_business_logs (id int8 not null, agent varchar(100), entry varchar(200) not null, ip varchar(100), operate_at timestamp not null, operation varchar(200) not null, operator varchar(50) not null, resrc varchar(100) not null, detail_id int8, primary key (id));
create table ems_code_categories (id int4 not null, name varchar(50) not null unique, parent_id int4, primary key (id));
create table ems_code_metas (id int8 not null, class_name varchar(100) not null, name varchar(50) not null unique, title varchar(100) not null, category_id int4 not null, primary key (id));
create table ems_code_scripts (id int8 not null, created_at timestamp, updated_at timestamp, attr varchar(20) not null, code_class_name varchar(100) not null, code_name varchar(40) not null, description varchar(100) not null, script varchar(500) not null, primary key (id));
create table ems_entity_metas (id int8 not null, comments varchar(255) not null, name varchar(255) not null, remark varchar(500), primary key (id));
create table ems_property_config_items (id int8 not null, description varchar(500) not null, name varchar(100) not null, type varchar(500) not null, value varchar(500) not null, primary key (id));
create table ems_property_metas (id int8 not null, comments varchar(40), name varchar(255) not null, remark varchar(100), type varchar(255) not null, meta_id int8 not null, primary key (id));
create table ems_rule_config_params (id int8 not null, value varchar(500) not null, config_id int8 not null, param_id int8 not null, primary key (id));
create table ems_rule_configs (id int8 not null, created_at timestamp, updated_at timestamp, enabled bool not null, rule_id int8 not null, primary key (id));
create table ems_rule_parameters (id int8 not null, description varchar(100) not null, name varchar(100) not null, title varchar(100) not null, type varchar(100) not null, parent_id int8, rule_id int8, primary key (id));
create table ems_rules (id int8 not null, created_at timestamp, updated_at timestamp, business varchar(100) not null, description varchar(300) not null, enabled bool not null, factory varchar(50) not null, name varchar(100) not null unique, service_name varchar(80) not null, primary key (id));
create table se_access_logs (id int8 not null, begin_at timestamp not null, end_at timestamp not null, resrc varchar(255) not null, sessionid varchar(255) not null, username varchar(255) not null, primary key (id));
create table se_authorities (id int8 not null, group_id int8 not null, resource_id int8 not null, primary key (id));
create table se_group_members (id int8 not null, created_at timestamp, updated_at timestamp, granter bool not null, manager bool not null, member bool not null, group_id int8 not null, user_id int8 not null, primary key (id));
create table se_group_profiles (id int8 not null, group_id int8, primary key (id));
create table se_group_properties (id int8 not null, value varchar(1000), meta_id int8 not null, profile_id int8 not null, primary key (id));
create table se_groups (id int8 not null, code varchar(30) not null, created_at timestamp, dynamic bool not null, enabled bool not null, name varchar(100) not null unique, remark varchar(255), updated_at timestamp, owner_id int8 not null, parent_id int8, primary key (id));
create table se_menu_profiles (id int8 not null, enabled bool not null, name varchar(50) not null unique, group_id int8 not null, primary key (id));
create table se_menus (id int8 not null, code varchar(30) not null, enabled bool not null, entry varchar(255), name varchar(100) not null, remark varchar(255), title varchar(100) not null, parent_id int8, profile_id int8 not null, primary key (id));
create table se_menus_resources (menu_id int8 not null, resource_id int8 not null, primary key (menu_id, resource_id));
create table se_property_metas (id int8 not null, key_name varchar(20), multiple bool not null, name varchar(50) not null unique, property_names varchar(100), remark varchar(255) not null, required bool not null, source varchar(200), value_type varchar(100) not null, primary key (id));
create table se_resources (id int8 not null, enabled bool not null, entry bool not null, name varchar(100) not null unique, remark varchar(100), scope int4 not null, title varchar(100) not null, primary key (id));
create table se_restrict_entities (id int8 not null, name varchar(255), remark varchar(255), type varchar(255), primary key (id));
create table se_restrictions (id int8 not null, content varchar(600) not null, enabled bool not null, remark varchar(200), resrc varchar(200), entity_id int8 not null, group_id int8, user_id int8, primary key (id));
create table se_session_profiles (id int8 not null, capacity int4 not null, inactive_interval int4 not null, user_max_sessions int4 not null, group_id int8 not null, primary key (id));
create table se_session_stats (id int8 not null, capacity int4 not null, category varchar(255) not null, inactive_interval int4 not null, on_line int4, stat_at timestamp not null, user_max_sessions int4 not null, primary key (id));
create table se_sessioninfo_logs (id varchar(255) not null, agent varchar(50), fullname varchar(50) not null, ip varchar(100), login_at timestamp not null, logout_at timestamp not null, online_time int8 not null, os varchar(50), remark varchar(100), username varchar(40) not null, primary key (id));
create table se_sessioninfoes (id varchar(255) not null, agent varchar(50), category varchar(255), expired_at timestamp, fullname varchar(50) not null, ip varchar(100), last_access_at timestamp, login_at timestamp not null, os varchar(50), remark varchar(100), username varchar(40) not null, primary key (id));
create table se_user_profiles (id int8 not null, user_id int8, primary key (id));
create table se_user_properties (id int8 not null, value varchar(1000), meta_id int8 not null, profile_id int8 not null, primary key (id));
create table se_users (id int8 not null, created_at timestamp, updated_at timestamp, effect_at timestamp not null, enabled bool not null, fullname varchar(50) not null, invalid_at timestamp, mail varchar(255) not null, name varchar(40) not null unique, password varchar(100) not null, password_expired_at timestamp, remark varchar(255), creator_id int8, primary key (id));
alter table ems_business_log_details add constraint FK5085C53CB554E7E5 foreign key (log_id) references ems_business_logs;
alter table ems_business_logs add constraint FK3289325A199B50E9 foreign key (detail_id) references ems_business_log_details;
alter table ems_code_categories add constraint FK3934D03AF0A5758D foreign key (parent_id) references ems_code_categories;
alter table ems_code_metas add constraint FK3D1FC630D0E770B9 foreign key (category_id) references ems_code_categories;
alter table ems_property_metas add constraint FK36E44E188EFB861B foreign key (meta_id) references ems_entity_metas;
alter table ems_rule_config_params add constraint FK88D1E11424380613 foreign key (param_id) references ems_rule_parameters;
alter table ems_rule_config_params add constraint FK88D1E1147E3855E2 foreign key (config_id) references ems_rule_configs;
alter table ems_rule_configs add constraint FK7172A22D5B0F821 foreign key (rule_id) references ems_rules;
alter table ems_rule_parameters add constraint FKA6B7399D5B0F821 foreign key (rule_id) references ems_rules;
alter table ems_rule_parameters add constraint FKA6B739959CC44D6 foreign key (parent_id) references ems_rule_parameters;
alter table se_authorities add constraint FK964E94B4F5DE1217 foreign key (group_id) references se_groups;
alter table se_authorities add constraint FK964E94B4B396151D foreign key (resource_id) references se_resources;
alter table se_group_members add constraint FKD501E02C590D297D foreign key (user_id) references se_users;
alter table se_group_members add constraint FKD501E02CF5DE1217 foreign key (group_id) references se_groups;
alter table se_group_profiles add constraint FKB6327737F5DE1217 foreign key (group_id) references se_groups;
alter table se_group_properties add constraint FKFDF7B940D95AEF63 foreign key (profile_id) references se_group_profiles;
alter table se_group_properties add constraint FKFDF7B94047BF7CD7 foreign key (meta_id) references se_property_metas;
alter table se_groups add constraint FKEE42686153164C0C foreign key (parent_id) references se_groups;
alter table se_groups add constraint FKEE426861C4F3D995 foreign key (owner_id) references se_users;
alter table se_menu_profiles add constraint FK99C2CB9DF5DE1217 foreign key (group_id) references se_groups;
alter table se_menus add constraint FK314882C7FEDB7EED foreign key (profile_id) references se_menu_profiles;
alter table se_menus add constraint FK314882C76FE76A3D foreign key (parent_id) references se_menus;
alter table se_menus_resources add constraint FK48E2AEAD2D262568 foreign key (menu_id) references se_menus;
alter table se_menus_resources add constraint FK48E2AEADB396151D foreign key (resource_id) references se_resources;
alter table se_restrictions add constraint FKB83F16F467F13DE5 foreign key (entity_id) references se_restrict_entities;
alter table se_restrictions add constraint FKB83F16F4590D297D foreign key (user_id) references se_users;
alter table se_restrictions add constraint FKB83F16F4F5DE1217 foreign key (group_id) references se_groups;
alter table se_session_profiles add constraint FKBBF365C0F5DE1217 foreign key (group_id) references se_groups;
alter table se_user_profiles add constraint FK60AB6EB1590D297D foreign key (user_id) references se_users;
alter table se_user_properties add constraint FKEE10BA3A285E8807 foreign key (profile_id) references se_user_profiles;
alter table se_user_properties add constraint FKEE10BA3A47BF7CD7 foreign key (meta_id) references se_property_metas;
alter table se_users add constraint FK31BF79DBB4092D7C foreign key (creator_id) references se_users;
create sequence seq_ems_business_log_details start 1 increment 1;
create sequence seq_ems_business_logs start 1 increment 1;
create sequence seq_ems_code_categories start 1 increment 1;
create sequence seq_ems_code_metas start 1 increment 1;
create sequence seq_ems_code_scripts start 1 increment 1;
create sequence seq_ems_entity_metas start 1 increment 1;
create sequence seq_ems_property_config_items start 1 increment 1;
create sequence seq_ems_property_metas start 1 increment 1;
create sequence seq_ems_rule_config_params start 1 increment 1;
create sequence seq_ems_rule_configs start 1 increment 1;
create sequence seq_ems_rule_parameters start 1 increment 1;
create sequence seq_ems_rules start 1 increment 1;
create sequence seq_se_access_logs start 1 increment 1;
create sequence seq_se_authorities start 1 increment 1;
create sequence seq_se_group_members start 1 increment 1;
create sequence seq_se_group_profiles start 1 increment 1;
create sequence seq_se_group_properties start 1 increment 1;
create sequence seq_se_groups start 1 increment 1;
create sequence seq_se_menu_profiles start 1 increment 1;
create sequence seq_se_menus start 1 increment 1;
create sequence seq_se_property_metas start 1 increment 1;
create sequence seq_se_resources start 1 increment 1;
create sequence seq_se_restrict_entities start 1 increment 1;
create sequence seq_se_restrictions start 1 increment 1;
create sequence seq_se_session_profiles start 1 increment 1;
create sequence seq_se_session_stats start 1 increment 1;
create sequence seq_se_user_profiles start 1 increment 1;
create sequence seq_se_user_properties start 1 increment 1;
create sequence seq_se_users start 1 increment 1;
