[#ftl]
[@b.head/]
[@b.toolbar title="菜单配置"]bar.addClose();[/@]
[@b.form action="!save" theme="list" title="info.module.detail"]
	[@b.textfield name="menuProfile.name" label="common.name" value="${menuProfile.name!}" required="true" maxlength="50"/]
	[@b.select name="menuProfile.category.id" label="entity.userCategory" required="true" style="width:100px;" items=categories option="id,title"/]
	[@b.formfoot]
		[@b.redirectParams/]
		<input type="hidden" name="menuProfile.id" value="${menuProfile.id!}" />
		[@b.reset/]&nbsp;&nbsp;[@b.submit value="action.submit"/]
	[/@]
[/@]
[@b.foot/]