[#ftl]
[@b.form action="!save" theme="list" title="新增参数"]
	[@b.textfield name="configNew.name" required="true" label="参数名称"/]
	[@b.textfield name="configNew.value" required="true" label="参数值"/]
	[@b.textfield name="configNew.type" required="true" label="类型"/]
	[@b.textfield name="configNew.description" required="true" label="说明"/]
	[@b.formfoot]
		[@b.submit value="保存"/]
	[/@]
[/@]